on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Assets

jobs:
    build:
        name: Upload Release Asset
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Dependencies
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm install

            - name: Build Project
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: tsc

            - name: Get the version
              id: get_version
              run: |
                  echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
                  echo ::set-output name=VERSION_NUMBER::${GITHUB_REF/refs\/tags\/v/}

            #Substitute the Manifest and Download URLs in the module.json
            - name: Substitute Manifest and Download Links For Versioned Ones
              id: sub_manifest_link_version
              uses: microsoft/variable-substitution@v1
              with:
                  files: 'module.json'
              env:
                  version: ${{ steps.get_version.outputs.VERSION_NUMBER }}
                  url: https://github.com/${{ github.repository }}
                  bugs: https://github.com/${{ github.repository }}/issues
                  #license: https://raw.githubusercontent.com/${{ github.repository }}/v${{ steps.get_version.outputs.VERSION_NUMBER }}/LICENSE
                  readme: https://raw.githubusercontent.com/${{ github.repository }}/v${{ steps.get_version.outputs.VERSION_NUMBER }}/README.md
                  manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
                  download: https://github.com/${{ github.repository }}/releases/download/v${{ steps.get_version.outputs.VERSION_NUMBER }}/module.zip

            # Zip Files
            - name: Zip files
              run: zip -r narrator-tools * -x ".github/*" "*.ts" "README.md" "tsconfig.json" "package.json"

            # Create a release for this specific version
            - name: Create Release
              id: create_version_release
              uses: ncipollo/release-action@v1
              with:
                  tag: ${{ steps.get_version.outputs.VERSION }}
                  name: Release ${{ steps.get_version.outputs.VERSION }}
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: 'module.json,./narrator-tools.zip'
